apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    svc: inventory
    app: inventory
spec:
  selector:
    matchLabels:
      svc: inventory
  replicas: 1
  template:
    metadata:
      labels:
        svc: inventory
        app: inventory
    spec:
      containers:
      - image: nginx
        name: inventory
        ports:
        - containerPort: 8080
