apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
  labels:
    svc: inventory-db
    app: inventory-db
spec:
  selector:
    matchLabels:
      svc: inventory-db
  replicas: 1
  template:
    metadata:
      labels:
        svc: inventory-db
        app: inventory-db
    spec:
      containers:
      - image: nginx
        name: inventory-db
        ports:
        - containerPort: 8080
