apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
  labels:
    svc: transaction
    app: transaction
spec:
  selector:
    matchLabels:
      svc: transaction
  replicas: 1
  template:
    metadata:
      labels:
        svc: transaction
        app: transaction
    spec:
      containers:
      - image: nginx
        name: transaction
        ports:
        - containerPort: 8080
